Use mignore when creating directorysnapshot
SamSchott/maestral pull request #219
Opened 2020-11-13 11:51 UTC by andrewsali

This PR uses a custom `listdir` function in `DirectorySnapshot` to take into account the `mignore` rules.

Using this PR, there is no need to snapshot ignored folders which can save considerable time and memory.

Fixes #216

## PR Checklist:

Note: there are no new features, just performance improvements
- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2020-11-13 22:56 UTC, SamSchott commented
Many thanks! I just rebased to the develop branch to fix a wrong import (the test failure). I'll have a look at the actual changes hopefully tomorrow.

2020-11-14 14:40 UTC, SamSchott requested changes
I have marked a few technical and code-style issues inline. A larger issue is that this PR (unintentionally?) changes the syncing behaviour: The content of folders which have been added to `.mignore` will now be deleted from the remote Dropbox if they have been previously synced. This happens because items which were deleted are identified by comparing the contents of the `DirectorySnapshot` to our index. And the content of an ignored folder will no longer show up in the snapshot...

This behaviour is contrary to to what is promised in the [wiki](https://github.com/SamSchott/maestral/wiki/mignore). The intention was to provide similar behaviour to gitignore where items that are already tracked will continue to be tracked even if they match a (new) ignore pattern. I'm not sure if this really is the right choice for a sync client. Selective sync behaves differently by removing newly excluded items from the local folder and maybe mignore should mirror that by removing newly excluded items from the remote server. I'm open for discussion here.

In any case, the choice needs to be consistent between an ignored folder and its children. With your current implementation, only the folder content will be removed. I can see two options:

1. Also exclude the matching item itself from the directory snapshot. This will result in a more complex listdir replacement.
2. Keep listing folders in the directory snapshot if they already in our index. This would require an additional call to `SyncEngine.get_index_entry` (which returns `None` if the item isn't in our index). If you pre-load the index before creating the snapshot, this won't incur any overhead fromdatabase queries. The relevant lines are: https://github.com/SamSchott/maestral/blob/864994733ad518fe5b3557cc1500d7050242095d/src/maestral/sync.py#L1827-L1829 Those would need to be moved to *before* creating the snapshot.

2020-11-14 14:40 UTC, SamSchott commented on src/maestral/sync.py
> +        )
`_is_mignore_path` takes a path relative to the Dropbox folder as argument. This is indicated by the argument name `dbx_path` as opposed to `local_path`. You'll need to convert the local path with `to_dbx_path` before passing it on as an argument. As it stands, there won't be any matches. Apologies for the missing documentation.

2020-11-17 15:07 UTC, andrewsali commented
Thanks for the comments!

1. path

I was aware of the issue regarding the Dropbox vs absolute path - however
the 'relative path' will also match the absolute path (e.g. test/testfile
will match /home/Dropbox/test/testfile)

The issue can be that someone puts home/Dropbox into ignore and wants to
actually exclude /home/Dropbox/home/Dropbox, whereas currently it will
exclude everything - not sure if this is a common case though, but should
be fixed.

2. sync behaviour

I think a common case is that people have files that they don't want in
Dropbox, but they only realise **after** having synced it already. If
mignore removes these files, then it's a clean solution, otherwise how can
it be removed from Dropbox without also deleting the local files?

Also, I think 'path dependence' (do I modify mignore before or after the
first sync) is not a very intuitive behaviour if the configuration files
themselves do not reflect path-dependence. For example, if I rsync the
Dropbox folder to another computer and get a different result when running
maestral, that's quite confusing. With git it makes sense as there is clear
storage of the history **inside the repository**. So if I rsync the repo to
a different computer, I still get the same behaviour.

3. listdir function

Agreed, the current listdir is incomplete, it doesn't handle files properly
and folders are still left empty. I can fix that.

On Sat, Nov 14, 2020, 15:41 SamSchott <notifications@github.com> wrote:

> *@SamSchott* requested changes on this pull request.
>
> I have marked a few technical and code-style issues inline. A larger issue
> is that this PR (unintentionally?) changes the syncing behaviour: The
> content of folders which have been added to .mignore will now be deleted
> from the remote Dropbox if they have been previously synced. This happens
> because items which were deleted are identified by comparing the contents
> of the DirectorySnapshot to our index. And the content of an ignored
> folder will no longer show up in the snapshot...
>
> This behaviour is contrary to to what is promised in the wiki
> <https://github.com/SamSchott/maestral/wiki/mignore>. The intention was
> to provide similar behaviour to gitignore where items that are already
> tracked will continue to be tracked even if they match a (new) ignore
> pattern. I'm not sure if this really is the right choice for a sync client.
> Selective sync behaves differently by removing newly excluded items from
> the local folder and maybe mignore should mirror that by removing newly
> excluded items from the remote server. I'm open for discussion here.
>
> In any case, the choice needs to be consistent between an ignored folder
> and its children. With your current implementation, only the folder content
> will be removed. I can see two options:
>
>    1. Also exclude the matching item itself from the directory snapshot.
>    This will result in a more complex listdir replacement.
>    2. Keep listing folders in the directory snapshot if they already in
>    our index. This would require an additional call to
>    SyncEngine.get_index_entry (which returns None if the item isn't in
>    our index). If you pre-load the index before creating the snapshot, this
>    won't incur any overhead fromdatabase queries. The relevant lines are:
>    https://github.com/SamSchott/maestral/blob/864994733ad518fe5b3557cc1500d7050242095d/src/maestral/sync.py#L1827-L1829
>    Those would need to be moved to *before* creating the snapshot.
>
> ------------------------------
>
> In src/maestral/sync.py
> <https://github.com/SamSchott/maestral/pull/219#discussion_r523420289>:
>
> > @@ -3633,6 +3633,12 @@ def _clean_history(self):
>              # commit to drive
>              self._db_session.commit()
>
> +    def _dir_snapshot_with_mignore(self, path: str) -> DirectorySnapshot:
> +        return DirectorySnapshot(
> +            path,
> +            listdir=lambda x: [] if self._is_mignore_path(x, True) else os.scandir(x),
> +        )
>
> I'm not too happy about using a lambda function here. It does not allow
> type hints and barely fits into a single line.
> ------------------------------
>
> In src/maestral/sync.py
> <https://github.com/SamSchott/maestral/pull/219#discussion_r523425354>:
>
> > @@ -3633,6 +3633,12 @@ def _clean_history(self):
>              # commit to drive
>              self._db_session.commit()
>
> +    def _dir_snapshot_with_mignore(self, path: str) -> DirectorySnapshot:
> +        return DirectorySnapshot(
> +            path,
> +            listdir=lambda x: [] if self._is_mignore_path(x, True) else os.scandir(x),
> +        )
>
> _is_mignore_path takes a path relative to the Dropbox folder as argument.
> This is indicated by the argument name dbx_path as opposed to local_path.
> You'll need to convert the local path with to_dbx_path before passing it
> on as an argument. As it stands, there won't be any matches. Apologies for
> the missing documentation.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SamSchott/maestral/pull/219#pullrequestreview-530578301>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTBRJ5TH2HTVFFIYCOTH6TSP2JIBANCNFSM4TUPTT6Q>
> .
>

2020-11-18 01:37 UTC, SamSchott commented
1. Regarding the path handling: I don't think that a `test/testfile` pattern will match `/home/Dropbox/test/testfile`. From the gitignore documentation:

   > If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself

   This also fits with my tests.  So to have patterns which act relative to the Dropbox directory, one must indeed compare them against a `dbx_path`. Or did I misunderstand you?

2. Sync behaviour: Those are all good points. As you note:

   > otherwise how can it be removed from Dropbox without also deleting the local files?

   I was initially targeting use cases where the excluded files can indeed be deleted locally without issues because they are byproducts which would just clutter the Dropbox folder for other collaborators (e.g., build logs, etc). But I can follow your argument. If we take your route, it would currently require a pause / resume cycle to trigger the deletion from the remote Dropbox, as is currently needed to resync an item after removing an entry from `mignore`.  

    I think I'm fine with this change as long as 3. is fixed. In the long term, maybe a more explicit interface would be good.

2020-12-20 15:25 UTC, SamSchott commented
@andrewsali, are you still planning to make the changes? This PR would be a welcome improvement.

2020-12-20 15:33 UTC, andrewsali commented
Yes, sorry had a very hectic end of year - I am planning to make the
discussed changes still in 2020

On Sun, Dec 20, 2020, 16:25 SamSchott <notifications@github.com> wrote:

> @andrewsali <https://github.com/andrewsali>, are you still planning to
> make the changes? This PR would be a welcome improvement.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SamSchott/maestral/pull/219#issuecomment-748621819>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTBRJ4AV4H3LNAPMHAJNTLSVYJPXANCNFSM4TUPTT6Q>
> .
>

2020-12-20 15:34 UTC, SamSchott commented
Ok, thanks! There is no rush really, just wanted to check in.

2021-01-14 16:06 UTC, andrewsali commented
@SamSchott I have made the changes I believe :)

2021-01-15 00:44 UTC, SamSchott commented
The test failure is on me, it's indeed introduced in bc25d9d1013f9c73bc1a7b121dd063190271e24f. I tried to fix this now in the subsequent commits. Could you try rebasing to the dev branch again?

2021-01-15 09:25 UTC, andrewsali commented
I re-pushed, but the test has been running four hours, not sure if this is expected

2021-01-15 13:39 UTC, SamSchott commented
No, it should only take 20 - 30 min. It looks like a deadlock somewhere because desktop notifications are not available on a headless system. I'll try to reproduce this locally. That goes to show: always create pull requests instead of committing directly...

In any case, I'll aim to have another look at your code this weekend.

2021-01-18 16:26 UTC, SamSchott approved these changes
Looks good to me, thank you for the good work!

I've also fixed the deadlock in the Ubuntu tests. Can you rebase to the develop branch again? Then I'll merge.

2021-01-19 08:08 UTC, andrewsali commented
Great, thx, rebased

2021-01-19 10:09 UTC, merged